### ISSUE TITLE
Choosing to display an annotation GTS does not rescale the graph even if the time range is wider

### ISSUE THREAD

**Issue by hbs** [cityzendata/warp10-quantum#19]

**Comment by StevenLeRoux** [comment]
I'm experiencing a bug that could be related to this one.

While fetching series with mutliple stacks, one being dedicated to annotations, if the annotation serie is empty, there is not graph to be deplayed even for other stacks.

Disabling the annotation serie renders the graph. 

If I enable again the annotation (empty GTS), I can't refresh the graph anymore.

Console is printing : 

```
Uncaught TypeError: Cannot read property '0' of undefined
    at Object.c.gtsTimeRange (quantum-app.html:65)
    at Object.a.getGtsListRange (quantum-plot.html:1)
    at HTMLElement._dataToChart (quantum-plot.html:1)
    at HTMLElement.<anonymous> (quantum-plot.html:1)
    at k.complete (quantum-app.html:1)
    at boundComplete (quantum-app.html:1)
```

**Comment by miton18** [comment]
https://github.com/cityzendata/warp10-quantumviz/pull/26
and 
https://github.com/cityzendata/warp10-iron/pull/4

should solve this

**Comment by LostInBrittany** [comment]
IT was a different one indeed, and @miton18 fixed it very quickly :) Thanks!
