### ISSUE TITLE
Large LONG values show as annotations

### ISSUE THREAD

**Issue by hbs** [cityzendata/warp10-quantum#44]
The following WarpScript snippet does not display properly in Quantum.

'60VBNLGnNaKsNqWWQaS_5k5705_YNLw5B201BJO14V.L.0g..4N.5AV2u3k.0KVrcEJrk5DNcXhh92YDbe5w.V.LR..Ay.B.YZvFZxoaNsrxHPE1WYb.aXL.zkTDIdyxrcF0NtXWWcHWwamznqzz.ctinxai79n7xzEmOAyP8UzdjmaDQg2UsKahjUyHick0c78SV7as9NlDzsIcjjR1NsrRkAph.UTVnG9.yQS.X5uFXh3muUzXnAj..dzC3V.Yu..30F..YZvVXPxCNtX1Zw7zhY1UnGAzVsVoY5ukx9WWi8bHXi5N.xq5_k9.VEYz.Nl8jziaf.8YYSip7ElH0c2qromDLF1.V91n.NWikDIH5EzGaBnc4QvinV7.7yV.0BUyV7tiV8n2ADfosSXmFtzC3jzyWkmDId2QlPc0NtX1vs6KDzzUtnUzzwwqYZuzehUv.LDCqvIHMh.LVAK9V71NFcWikEuBsUV1lhXS_df_392C3V.LR..Ay.Y.X4Z..2l7..js1B17IhzloEIp.aDNXuitNibZrtm1.F.Yu...azp.Y5ujkdZofvM6ttqh.UqTrk5.yxw8YabkqzSuqgfQesug272t8sWivz9IUQidzjjBp.iTvE30.1Ec..1XzF.L9W7.' UNWRAP

**Comment by LostInBrittany** [comment]
hmmmm, Yeah, that's a long bigger than [Number.MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER) and to keep the precision we use [big.js](https://github.com/MikeMcl/big.js/), but the underlying graphics lib doesn't understand that... 

Going to try a quick fix...
