### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by urcadox** [cityzendata/warp10-quantum#47]
Hello,

While I can run `polymer serve` just fine, running `polymer build` fails with the following error:

```
error:   Promise rejection: Error: ENOENT: no such file or directory, open '/home/urcadox/dev/clevercloud/warp10-quantum/bower_components/polymer/polymer-element.html'
error:   Error: ENOENT: no such file or directory, open '/home/urcadox/dev/clevercloud/warp10-quantum/bower_components/polymer/polymer-element.html'
```

In the polymer directory, I have `polymer.html`, `polymer-micro.html` and `polymer-mini.html` but no `polymer-element.html`. Is this a version issue maybe?

By the way, are there any plans to switch away from bower towards something with a lock file?

Thanks!

**Comment by LostInBrittany** [comment]
Hello Alexandre!

I think it could be a version issue, yeah… Could you please delete your
bower_components
folder and do a bower install again ? I’m going to do the same thing on my
side to
try to reproduce.

Regards,

Horacio Gonzalez
DevRel OVH
​

**Comment by Giwi** [comment]
Hi Alexandre,  we need to stay up to date, indeed, but, polymer is shipped with bower : https://www.polymer-project.org/2.0/start/install-2-0 
I will investigate your bug as soon as possible.

Rgds.
Xavier

**Comment by urcadox** [comment]
I've already removed bower_components before each try. :)

I will try to remove everything again and use the bower shipped with polymer then.

**Comment by LostInBrittany** [comment]
What version of `polymer-cli` are you using?

**Comment by urcadox** [comment]
I was using 1.5.7, the latest version published on npm.

**Comment by LostInBrittany** [comment]
Ok, thats's weird...
I have just deleted my `bower_components`, done a `bower install` and then built again : 
```
horacio@horacio:~/git/warp10-quantum$ polymer build
info:    Clearing build/ directory...
info:    (unbundled) Building...
info:    (bundled) Building...
info:    (unbundled) Build complete!
info:    (bundled) Build complete!
horacio@horacio:~/git/warp10-quantum$ polymer --version
1.5.7
horacio@horacio:~/git/warp10-quantum$ 
```

**Comment by Giwi** [comment]
Have you tried : 
`rm -rf bower_components
bower cache clean
bower install`

**Comment by urcadox** [comment]
It's now working after installing explicitly polymer in version 2.0 (which prompted me to choose again the version among 13 because of dependencies depending on different versions; I selected "polymer#^2.0.0 which resolved to 2.3.1").

**Comment by urcadox** [comment]
I guess just updating the bower.json should be fine then. It's currently set at `1.0.0` in depedencies and `1.9.0` in resolutions.

**Comment by LostInBrittany** [comment]
Yeah, Quantum depends explicitly on Polymer 2.x.
But bower should be able to solve it without problem.
Currently in bower.json the dependency is 2.0, at least for me...
https://github.com/cityzendata/warp10-quantum/blob/master/bower.json

```
"dependencies": {
    "polymer": "polymer/polymer#~2.2.0",
```

Are you sure you have a clean version?

**Comment by urcadox** [comment]
Oh forgot to mention that. I'm trying to use version 2.6.7 (which is the one currently set for warp10 standalone).

Is this fixed in 2.7.0 maybe? I got lost in the tags to be honest. It's a bit confusing seeing as the only release notes are for 2.4.0 (or so I found).

**Comment by LostInBrittany** [comment]
Yeah, we have fixed many errors and bugs in recent months. Old versions like the one you use can be not very stable...
Could you please upgrade to last version?

**Comment by LostInBrittany** [comment]
I forgot... IMHO warp10-standalone should upgrade to warp10-quantum 3.x. 2.6.7 is indeed problematic. Maybe we should post an issue there?

**Comment by urcadox** [comment]
I guess so, yes.

Anyway, I will use the 3 rc1 then.

Thanks @Giwi and @LostInBrittany!
