### ISSUE TITLE
Two last digits of large integers ignored when displayed

### ISSUE THREAD

**Issue by juanmaneo** [cityzendata/warp10-quantum#7]
When using WarpScript Quantum console large integer like timestamps in nanoseconds last two digits are ignored.

Example: 
1456237803863468066
DUP
100 %

Gives:
0: 66
1: 1456237803863468000

Instead of:
0: 66
1: 14562378038634680**66**

**Comment by LostInBrittany** [comment]
It's a limitation of JavaScript. In JavaScript you don't have a `long` type, you have a `number` and the maximum safe integer ( cf [Number.MAX_SAFE_INTEGER](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER) ) is 9007199254740991 (2^53 - 1).

As Quantum is a JS application, integer values bigger than that maximum safe integer are natively rounded. As usually we work with TS in microseconds, it isn't an issue we have found often. 

I'm looking for a way to deal with bigger integer without making code too complex. Suggestions are welcome, of course !

**Comment by LostInBrittany** [comment]
BTW, today's Quantum implementations works with timestamps in microseconds. Is there a need to make it work with other time units?

**Comment by hbs** [comment]
They use timestaps in ns, so yes, there is a need to make it work with all supported time units, or clearly display a warning saying it won't.

**Comment by LostInBrittany** [comment]
That would be another issue, different from the JavaScript max safe integer. I'm keeping this issue for the  JavaScript max safe integer and creating a new one for the use of different time units in Quantum

**Comment by juanmaneo** [comment]
Hi,

Thanks for the explanations and help.
@LostInBrittany,  I think you answered how to deal with bigger integer at least for timestamp.

First here is how I understand what's happening:
Warp10 platform does all the calculation with timestamp so it needs an integer type.
Quantum is only displaying the timestamp as far as I know ? So a timestamp shall not be an integer in Quantum but digits stored as a string. My educated guess is that: there is a serialization/de-serialization that transform it to integer in Quantum ?

Would it be difficult complex to handle timestamp as string in Quantum ?
Is there a need for a timestamp as an integer type ? Perhaps for the graph tool ?
If it's the case one solution I see, is too add a constructed object that handle the transformation from string to a decimal value that can handle nanoseconds. 
The decimal value can be coded either in vanilla javascript by separating the nanoseconds that we loose or using a decimal arbitrary library like https://github.com/MikeMcl/bignumber.js

What do you think?

**Comment by LostInBrittany** [comment]
In fact, the precision lost is made in Quantum when it receives the JSON response from the server. 
The JSON is parsed, and while parsing it reads the value (it's a number in the JSON, as it should be) and maps it to a JavaScript `number` introducing the error.

It doesn't happens only with timestamp (even if it's the most usual rounding problem if using platforms with time units in ns), but with any "big" `long` value.

Today we already use a non standard JSON parser, [warp10-looseJSON»(https://github.com/cityzendata/warp10-iron/blob/master/warp10-looseJSON.html) in the [warp10-iron»(https://github.com/cityzendata/warp10-iron) utilities package. I can try to use a library like `bignumber.js` (thanks for the idea!) in it to make the right parsing.

The plotting tool need timestamps to be `number` or `date`, but I think I could make it work with `bignumber.js` too.

**Comment by juanmaneo** [comment]
Thanks for explanation,

That is was I thought. Happy to see we have a bigger understanding of this issue.

Keep the good work!

**Comment by LostInBrittany** [comment]
The problem is solved in the WarpScript IDE panel. 
If's also solved when used big integers as values in plot.

But there is still a problem with plotting GTS with big int in timestamp,
i.e. with timebase in ns.  Trying to solve it with #8 issue.
